name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.x

      - name: Build web app
        run: flutter build web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          permissions:
            actions: write
            deployments: write
            id-token: write
            packages: write
            pages: write
            pull-requests: write
            repository-projects: write
            security-events: write
            statuses: write
          publish_branch: gh-pages
          publish_dir: build/web
