name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Build web app
        run: flutter build web

      - name: Copy build files to root
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
        run: |
          rsync -a build/web/ ./

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: web
